### ISSUE TITLE
Many equivalence axioms should be translated to subclassOf axioms

### ISSUE THREAD

**Issue by cmungall** [carrineblank/MicrO#2]
e.g.

```
antimicrobial resistance assay:
EquivalentTo
'antimicrobial assay'
 and ('uses chemical reagent' some 'chemical entity')
```

You can see the consequences of this, e.g. look at ''growth factor requirement assay' after turning on the reasoner

**Comment by carrineblank** [comment]
The issues in the part of the ontology have been fixed by 

1) fixing the axiom for 'X + V factor disc'
2) changing the antimicrobial resistance assay equivalence axioms, changing class names, and reordering the classes to mirror analogous classes in GO regarding:
'response to chemical'
   'response to toxic substance'
      'response to antibiotic'
   response to organic substance'
      'response to bile acid'
      'response to growth factor'
   'response to inorganic substance'
      'response to lithium ion'
3) examining consequences by invoking the reasoner.

I will keep my eye out for similar issues in other parts of the ontology.

Thanks!

**Comment by carrineblank** [comment]
FYI,

Several additional axioms with similar issues were corrected in other parts of the ontology.
