### ISSUE TITLE
Nesting incorrect for measurement of pH growth assay

### ISSUE THREAD

**Issue by cmungall** [carrineblank/MicrO#3]
```
'pH growth assay'
 and ('uses chemical reagent' some 
    ((hydron
     or hydroxide)
     and ('has quality' some 
        (acidity
         and (
              ('has measurement' some ('has unit' value pH))
         and  ('has magnitude' value 5.0))))))
```

I believe the intent is that the magnitude is a property of the measurement, not the quality. Consider reaching out to the OBI people for descign patterns here.

**Comment by carrineblank** [comment]
Couple things to address this issue:

1) Nesting has been (hopefully) corrected.  I've found that Protege can sometimes rearrange parentheses (although in this case misplacement was likely my error) so I've tried to simplify these axioms to reduce this.
2) Contacted Jim Balhoff about the structure of thee axioms, because I had used his New Caledonia owl file as a model.
3) 'has measurement unit label' and 'has measurement value' have been borrowed from OBI in replacement of 'has unit' and 'has magnitude' terms.
4) Discussions are ongoing with Obi-devel to make sure that assays in MicrO and OBI are harmonized.  

-Carrine
